name: Protochat Build

on: [push]

jobs:
  build:
    
    name: Androi Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      # remove symbolic link and copy the real assets
      - run: rm assets
      - run: cp -R ./public/assets/ ./assets/
      - run: npm install -g @ionic/cli
      - run: npm install
      - run: npm run build:css
      - run: npm run build
      - run: npm run ionic:sync
      - name: Build debug APK
        working-directory: ./android
        run: bash ./gradlew --no-daemon --stacktrace assembleDebug
      - name: Build APK
        working-directory: ./android
        run: bash ./gradlew --no-daemon --stacktrace build
      - name: rename APKs
        run: find ./android -depth -name "*.apk" -print0 -exec sh -c 'mv "$1" $(dirname "$1")/protochat.apk' _ {} \;
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Protochat
          path: ./android/**/*.apk
