name: Protochat Build

on: [push]

jobs:
  build:
    
    name: Androi Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: npm install -g @ionic/cli
      - run: npm install --also=dev
      - run: npm run build:css
      - run: npm run build
      - run: npm run ionic:sync
      - run: cd ./android
      - name: Build debug APK
        run: bash ./android/gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Protochat
          path: app/**/*.apk
      - run: cd ..